//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Отчёт об оценке.
    /// </summary>
    // *** Start programmer edit section *** (ОтчётОбОценке CustomAttributes)

    // *** End programmer edit section *** (ОтчётОбОценке CustomAttributes)
    [AutoAltered()]
    [Caption("Отчёт об оценке")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОтчётОбОценкеE", new string[] {
            "ДатаСоздания as \'Дата создания\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.ФИО as \'ФИО\'",
            "Сотрудники.Должность as \'Должность\'"}, Hidden=new string[] {
            "Сотрудники.ФИО"})]
    [AssociatedDetailViewAttribute("ОтчётОбОценкеE", "ОценкаПодробно", "ОценкаПодробноE", true, "", "Оценка подробно", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ОтчётОбОценкеE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ОтчётОбОценкеL", new string[] {
            "ДатаСоздания as \'Дата создания\'",
            "Сотрудники.ФИО as \'ФИО\'"})]
    public class ОтчётОбОценке : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаСоздания = System.DateTime.Now;
        
        private IIS.Proekt3.Сотрудники fСотрудники;
        
        private IIS.Proekt3.DetailArrayOfОценкаПодробно fОценкаПодробно;
        
        // *** Start programmer edit section *** (ОтчётОбОценке CustomMembers)

        // *** End programmer edit section *** (ОтчётОбОценке CustomMembers)

        
        /// <summary>
        /// ДатаСоздания.
        /// </summary>
        // *** Start programmer edit section *** (ОтчётОбОценке.ДатаСоздания CustomAttributes)

        // *** End programmer edit section *** (ОтчётОбОценке.ДатаСоздания CustomAttributes)
        public virtual System.DateTime ДатаСоздания
        {
            get
            {
                // *** Start programmer edit section *** (ОтчётОбОценке.ДатаСоздания Get start)

                // *** End programmer edit section *** (ОтчётОбОценке.ДатаСоздания Get start)
                System.DateTime result = this.fДатаСоздания;
                // *** Start programmer edit section *** (ОтчётОбОценке.ДатаСоздания Get end)

                // *** End programmer edit section *** (ОтчётОбОценке.ДатаСоздания Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчётОбОценке.ДатаСоздания Set start)

                // *** End programmer edit section *** (ОтчётОбОценке.ДатаСоздания Set start)
                this.fДатаСоздания = value;
                // *** Start programmer edit section *** (ОтчётОбОценке.ДатаСоздания Set end)

                // *** End programmer edit section *** (ОтчётОбОценке.ДатаСоздания Set end)
            }
        }
        
        /// <summary>
        /// Отчёт об оценке.
        /// </summary>
        // *** Start programmer edit section *** (ОтчётОбОценке.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (ОтчётОбОценке.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Proekt3.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (ОтчётОбОценке.Сотрудники Get start)

                // *** End programmer edit section *** (ОтчётОбОценке.Сотрудники Get start)
                IIS.Proekt3.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (ОтчётОбОценке.Сотрудники Get end)

                // *** End programmer edit section *** (ОтчётОбОценке.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчётОбОценке.Сотрудники Set start)

                // *** End programmer edit section *** (ОтчётОбОценке.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (ОтчётОбОценке.Сотрудники Set end)

                // *** End programmer edit section *** (ОтчётОбОценке.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Отчёт об оценке.
        /// </summary>
        // *** Start programmer edit section *** (ОтчётОбОценке.ОценкаПодробно CustomAttributes)

        // *** End programmer edit section *** (ОтчётОбОценке.ОценкаПодробно CustomAttributes)
        public virtual IIS.Proekt3.DetailArrayOfОценкаПодробно ОценкаПодробно
        {
            get
            {
                // *** Start programmer edit section *** (ОтчётОбОценке.ОценкаПодробно Get start)

                // *** End programmer edit section *** (ОтчётОбОценке.ОценкаПодробно Get start)
                if ((this.fОценкаПодробно == null))
                {
                    this.fОценкаПодробно = new IIS.Proekt3.DetailArrayOfОценкаПодробно(this);
                }
                IIS.Proekt3.DetailArrayOfОценкаПодробно result = this.fОценкаПодробно;
                // *** Start programmer edit section *** (ОтчётОбОценке.ОценкаПодробно Get end)

                // *** End programmer edit section *** (ОтчётОбОценке.ОценкаПодробно Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчётОбОценке.ОценкаПодробно Set start)

                // *** End programmer edit section *** (ОтчётОбОценке.ОценкаПодробно Set start)
                this.fОценкаПодробно = value;
                // *** Start programmer edit section *** (ОтчётОбОценке.ОценкаПодробно Set end)

                // *** End programmer edit section *** (ОтчётОбОценке.ОценкаПодробно Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОтчётОбОценкеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтчётОбОценкеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтчётОбОценкеE", typeof(IIS.Proekt3.ОтчётОбОценке));
                }
            }
            
            /// <summary>
            /// "ОтчётОбОценкеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтчётОбОценкеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтчётОбОценкеL", typeof(IIS.Proekt3.ОтчётОбОценке));
                }
            }
        }
    }
}
