//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Причины.
    /// </summary>
    // *** Start programmer edit section *** (Причины CustomAttributes)

    // *** End programmer edit section *** (Причины CustomAttributes)
    public enum Причины
    {
        
        // *** Start programmer edit section *** (Причины.ПоСобственному CustomAttributes)

        // *** End programmer edit section *** (Причины.ПоСобственному CustomAttributes)
        [Caption("ПоСобственному")]
        ПоСобственному,
        
        // *** Start programmer edit section *** (Причины.Работодатель CustomAttributes)

        // *** End programmer edit section *** (Причины.Работодатель CustomAttributes)
        [Caption("Работодатель")]
        Работодатель,
        
        // *** Start programmer edit section *** (Причины.Пенсия CustomAttributes)

        // *** End programmer edit section *** (Причины.Пенсия CustomAttributes)
        [Caption("Пенсия")]
        Пенсия,
    }
}
