//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Статусы.
    /// </summary>
    // *** Start programmer edit section *** (Статусы CustomAttributes)

    // *** End programmer edit section *** (Статусы CustomAttributes)
    public enum Статусы
    {
        
        // *** Start programmer edit section *** (Статусы.Успешно CustomAttributes)

        // *** End programmer edit section *** (Статусы.Успешно CustomAttributes)
        [Caption("Успешно")]
        Успешно,
        
        // *** Start programmer edit section *** (Статусы.Безуспешно CustomAttributes)

        // *** End programmer edit section *** (Статусы.Безуспешно CustomAttributes)
        [Caption("Безуспешно")]
        Безуспешно,
    }
}
