//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Увольнение.
    /// </summary>
    // *** Start programmer edit section *** (Увольнение CustomAttributes)

    // *** End programmer edit section *** (Увольнение CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("УвольнениеE", new string[] {
            "ДатаУвольнения as \'Дата увольнения\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.ФИО as \'ФИО\'",
            "Сотрудники.Должность as \'Должность\'",
            "Сотрудники.Ранг as \'Ранг\'",
            "Причина as \'Причина\'"}, Hidden=new string[] {
            "Сотрудники.ФИО"})]
    [MasterViewDefineAttribute("УвольнениеE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("УвольнениеL", new string[] {
            "ДатаУвольнения as \'Дата увольнения\'",
            "Сотрудники.ФИО as \'ФИО\'",
            "Причина as \'Причина\'"})]
    public class Увольнение : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаУвольнения;
        
        private IIS.Proekt3.Причины fПричина;
        
        private IIS.Proekt3.Сотрудники fСотрудники;
        
        // *** Start programmer edit section *** (Увольнение CustomMembers)

        // *** End programmer edit section *** (Увольнение CustomMembers)

        
        /// <summary>
        /// ДатаУвольнения.
        /// </summary>
        // *** Start programmer edit section *** (Увольнение.ДатаУвольнения CustomAttributes)

        // *** End programmer edit section *** (Увольнение.ДатаУвольнения CustomAttributes)
        public virtual System.DateTime ДатаУвольнения
        {
            get
            {
                // *** Start programmer edit section *** (Увольнение.ДатаУвольнения Get start)

                // *** End programmer edit section *** (Увольнение.ДатаУвольнения Get start)
                System.DateTime result = this.fДатаУвольнения;
                // *** Start programmer edit section *** (Увольнение.ДатаУвольнения Get end)

                // *** End programmer edit section *** (Увольнение.ДатаУвольнения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Увольнение.ДатаУвольнения Set start)

                // *** End programmer edit section *** (Увольнение.ДатаУвольнения Set start)
                this.fДатаУвольнения = value;
                // *** Start programmer edit section *** (Увольнение.ДатаУвольнения Set end)

                // *** End programmer edit section *** (Увольнение.ДатаУвольнения Set end)
            }
        }
        
        /// <summary>
        /// Причина.
        /// </summary>
        // *** Start programmer edit section *** (Увольнение.Причина CustomAttributes)

        // *** End programmer edit section *** (Увольнение.Причина CustomAttributes)
        public virtual IIS.Proekt3.Причины Причина
        {
            get
            {
                // *** Start programmer edit section *** (Увольнение.Причина Get start)

                // *** End programmer edit section *** (Увольнение.Причина Get start)
                IIS.Proekt3.Причины result = this.fПричина;
                // *** Start programmer edit section *** (Увольнение.Причина Get end)

                // *** End programmer edit section *** (Увольнение.Причина Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Увольнение.Причина Set start)

                // *** End programmer edit section *** (Увольнение.Причина Set start)
                this.fПричина = value;
                // *** Start programmer edit section *** (Увольнение.Причина Set end)

                // *** End programmer edit section *** (Увольнение.Причина Set end)
            }
        }
        
        /// <summary>
        /// Увольнение.
        /// </summary>
        // *** Start programmer edit section *** (Увольнение.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (Увольнение.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Proekt3.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (Увольнение.Сотрудники Get start)

                // *** End programmer edit section *** (Увольнение.Сотрудники Get start)
                IIS.Proekt3.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (Увольнение.Сотрудники Get end)

                // *** End programmer edit section *** (Увольнение.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Увольнение.Сотрудники Set start)

                // *** End programmer edit section *** (Увольнение.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (Увольнение.Сотрудники Set end)

                // *** End programmer edit section *** (Увольнение.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "УвольнениеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УвольнениеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УвольнениеE", typeof(IIS.Proekt3.Увольнение));
                }
            }
            
            /// <summary>
            /// "УвольнениеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УвольнениеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УвольнениеL", typeof(IIS.Proekt3.Увольнение));
                }
            }
        }
    }
}
